--- 
title: 'CC Primer: Compute Canada for geoscientists in a rush'
author: "Ricardo Barros Lourenco"
date: 'Last revision: `r Sys.Date()`'
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
csl: ieee.csl
url: https://ricardobarroslourenco.github.io/CCprimer/
description: |
  Descricao (campo)
link-citations: yes
github-repo: ricardobarroslourenco/CCprimer
---
# Front Matter

## Copyright

Otherwise stated in the text, this content is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).

### How to cite this work
Please use this BibTeX fragment:

```{r, eval=FALSE}
@book{BarrosLourenco2022,
  title     = "CC Primer: Compute Canada for geoscientists in a rush",
  author    = "Barros Lourenco, Ricardo",
  year      = 2022,
  doi       = "10.5281/zenodo.5937906"
  note      = {\url{https://ricardobarroslourenco.github.io/CCprimer/}(visited yyyy-mm-dd)}
}
```

Obs.: Note that the DOI is of the base version (10.5281/zenodo.5937906) when 
compared to each revision releases, because it relates to all versions
of this document, rather than a especific one.

## Dedication
The author dedicates this work to all geoscientists that are trying to cross the
border into Computational Sciences, and to all computer scientists, mathematicians,
physicists, and other professionals who daily contribute in this community, 
by writing code, documenting, answering questions, maintaining infrastructure, 
among many other essential tasks. Thank you for your service!

## Epigraph
> "Here's to the crazy ones.
> The misfits.
> The rebels.
> The troublemakers.
> The round pegs in the square holes.
>
> The ones who see things differently.
>
> They're not fond of rules.
> And they have no respect for the status quo.
>
> You can quote them, disagree with them, glorify or vilify them.
> About the only thing you can't do is ignore them.
>
> Because they change things.
>
> They push the human race forward.
>
> While some may see them as the crazy ones,
we see genius.
>
> Because the people who are crazy enough to think
they can change the world, are the ones who do."
>
> --- Apple Computer, _"Think different"_ campaign. TBWA-Chiat-Day.


<!-- ## Foreword -->

<!-- ## Preface -->

## Acknowledgements
The author would like to acknowledge the contibution of the general Open Source Science
 community, in especially the following entities:

- [Anaconda](https://www.anaconda.com/)
- [Digital Research Alliance of Canada](https://alliancecan.ca/) (formerly Compute Canada)
- [Globus](https://www.globus.org)
- [Pangeo Community](https://pangeo.io)
- [RockeR Project](https://rocker-project.org)
- [Vanessa Sochat](https://scholar.google.com/citations?user=RTF50S4AAAAJ)

The author would like to acknowledge support, in part, of the following on this 
work:

- Through my advisor, Prof. [Alemu Gonsamo](https://scholar.google.ca/citations?user=snRPOMkAAAAJ):
  - Natural Sciences and Engineering Research Council of Canada (NSERC), through its NSERC
Alliance program (Application: ALLRP 566310-21)
  - Canada Research Chair program (CRC-2019-00139)
- [McMaster University Centre for Climate Change](https://climate.mcmaster.ca) Research Seed Fund
- The Shared Hierarchical Academic Research Computing Network ([SHARCNET](https://www.sharcnet.ca/)), and
the Digital Research Alliance of Canada through its Research Allocation Competition, under the
2023 Resources for Research Groups process “National carbon flux estimation system for forest
ecosystems of Canada” (ID 4715)

<!-- ## List of abbreviations and acronyms -->

## Cronology
2023-10-13 - v1.0 - First release, after several reviews.

2022-01-31 - v0.1 - Beginning.

<!-- --- Supressed from the template --- -->
<!-- ## Usage  -->

<!-- Each **bookdown** chapter is an .Rmd file, and each .Rmd file can contain one (and only one) chapter. A chapter *must* start with a first-level heading: `# A good chapter`, and can contain one (and only one) first-level heading. -->

<!-- Use second-level and higher headings within chapters like: `## A short section` or `### An even shorter section`. -->

<!-- The `index.Rmd` file is required, and is also your first book chapter. It will be the homepage when you render the book. -->

<!-- ## Render book -->

<!-- You can render the HTML version of this example book without changing anything: -->

<!-- 1. Find the **Build** pane in the RStudio IDE, and -->

<!-- 1. Click on **Build Book**, then select your output format, or select "All formats" if you'd like to use multiple formats from the same book source files. -->

<!-- Or build the book from the R console: -->

<!-- ```{r, eval=FALSE} -->
<!-- bookdown::render_book() -->
<!-- ``` -->

<!-- To render this example to PDF as a `bookdown::pdf_book`, you'll need to install XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.org/tinytex/>. -->

<!-- ## Preview book -->

<!-- As you work, you may start a local server to live preview this HTML book. This preview will update as you edit the book when you save individual .Rmd files. You can start the server in a work session by using the RStudio add-in "Preview book", or from the R console: -->

<!-- # ```{r eval=FALSE} -->
<!-- # bookdown::serve_book() -->
<!-- # ``` -->

